2020-05-13 08:11:27,254 DEBUG   MainThread:13877 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-05-13 08:11:27,262 DEBUG   MainThread:13877 [meta.py:setup():100] code probe starting
2020-05-13 08:11:27,264 DEBUG   MainThread:13877 [meta.py:_setup_code_git():49] probe for git information
2020-05-13 08:11:27,282 DEBUG   MainThread:13877 [meta.py:_setup_code_program():58] save program starting
2020-05-13 08:11:27,283 DEBUG   MainThread:13877 [meta.py:_setup_code_program():60] save program starting: /home/datta/lab/HPE3D/src/train.py
2020-05-13 08:11:27,283 DEBUG   MainThread:13877 [meta.py:_setup_code_program():68] save program saved: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/code/src/train.py
2020-05-13 08:11:27,283 DEBUG   MainThread:13877 [meta.py:_setup_code_program():70] save program
2020-05-13 08:11:27,284 DEBUG   MainThread:13877 [meta.py:setup():122] code probe done
2020-05-13 08:11:27,305 DEBUG   MainThread:13877 [run_manager.py:__init__():546] Initialized sync for hpe/13kxw0pw
2020-05-13 08:11:27,309 INFO    MainThread:13877 [run_manager.py:wrap_existing_process():1148] wrapping existing process 13850
2020-05-13 08:11:27,309 WARNING MainThread:13877 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-05-13 08:11:27,377 INFO    MainThread:13877 [run_manager.py:init_run():927] system metrics and metadata threads started
2020-05-13 08:11:27,377 INFO    MainThread:13877 [run_manager.py:init_run():966] upserting run before process can begin, waiting at most 10 seconds
2020-05-13 08:11:27,744 INFO    Thread-14 :13877 [run_manager.py:_upsert_run():1051] saving patches
2020-05-13 08:11:27,798 INFO    Thread-14 :13877 [run_manager.py:_upsert_run():1055] saving pip packages
2020-05-13 08:11:27,800 INFO    Thread-14 :13877 [run_manager.py:_upsert_run():1057] initializing streaming files api
2020-05-13 08:11:27,802 INFO    Thread-14 :13877 [run_manager.py:_upsert_run():1064] unblocking file change observer, beginning sync with W&B servers
2020-05-13 08:11:27,803 INFO    MainThread:13877 [run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2020-05-13 08:11:27,812 INFO    MainThread:13877 [run_manager.py:_sync_etc():1272] entering loop for messages from user process
2020-05-13 08:11:27,814 INFO    MainThread:13877 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1589350287.Datta.13850.0", "policy": "live"}}
2020-05-13 08:11:28,264 INFO    Thread-3  :13877 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/config.yaml
2020-05-13 08:11:28,556 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/code/src/train.py
2020-05-13 08:11:28,558 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/requirements.txt
2020-05-13 08:11:28,562 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/output.log
2020-05-13 08:11:28,563 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/events.out.tfevents.1589350287.Datta.13850.0
2020-05-13 08:11:28,564 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/diff.patch
2020-05-13 08:11:28,565 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/wandb-metadata.json
2020-05-13 08:11:28,567 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/code/src
2020-05-13 08:11:28,568 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/code
2020-05-13 08:11:28,719 INFO    MainThread:13877 [run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2020-05-13 08:11:28,720 INFO    MainThread:13877 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-05-13 08:11:28,720 INFO    MainThread:13877 [run_manager.py:shutdown():1071] shutting down system stats and metadata service
2020-05-13 08:11:29,264 INFO    Thread-3  :13877 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/output.log
2020-05-13 08:11:29,264 INFO    Thread-3  :13877 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/wandb-history.jsonl
2020-05-13 08:11:29,266 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/wandb-events.jsonl
2020-05-13 08:11:29,268 INFO    Thread-3  :13877 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/wandb-summary.json
2020-05-13 08:11:29,384 INFO    MainThread:13877 [run_manager.py:shutdown():1085] stopping streaming files and file change observer
2020-05-13 08:11:30,268 INFO    Thread-3  :13877 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_061126-13kxw0pw/wandb-metadata.json
2020-05-13 08:11:31,932 INFO    MainThread:13877 [run_manager.py:_sync_etc():1400] rendering summary
2020-05-13 08:11:31,933 INFO    MainThread:13877 [run_manager.py:_sync_etc():1433] syncing files to cloud storage
2020-05-13 08:11:33,192 INFO    MainThread:13877 [run_manager.py:_sync_etc():1448] syncing complete: https://app.wandb.ai/b-sridatta/hpe/runs/13kxw0pw
w/wandb-metadata.json
2020-05-13 08:11:31,932 INFO    MainThread:13877 [13kxw0pw:run_manager.py:_sync_etc():1400] rendering summary
2020-05-13 08:11:31,933 INFO    MainThread:13877 [13kxw0pw:run_manager.py:_sync_etc():1433] syncing files to cloud storage
2020-05-13 08:11:33,192 INFO    MainThread:13877 [13kxw0pw:run_manager.py:_sync_etc():1448] syncing complete: https://app.wandb.ai/b-sridatta/hpe/runs/13kxw0pw
