2020-05-12 20:31:23,171 DEBUG   MainThread:11642 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-05-12 20:31:23,176 DEBUG   MainThread:11642 [meta.py:setup():100] code probe starting
2020-05-12 20:31:23,178 DEBUG   MainThread:11642 [meta.py:_setup_code_git():49] probe for git information
2020-05-12 20:31:23,190 DEBUG   MainThread:11642 [meta.py:_setup_code_program():58] save program starting
2020-05-12 20:31:23,190 DEBUG   MainThread:11642 [meta.py:_setup_code_program():60] save program starting: /home/datta/lab/HPE3D/src/train.py
2020-05-12 20:31:23,191 DEBUG   MainThread:11642 [meta.py:_setup_code_program():68] save program saved: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/code/src/train.py
2020-05-12 20:31:23,191 DEBUG   MainThread:11642 [meta.py:_setup_code_program():70] save program
2020-05-12 20:31:23,191 DEBUG   MainThread:11642 [meta.py:setup():122] code probe done
2020-05-12 20:31:23,196 DEBUG   MainThread:11642 [run_manager.py:__init__():546] Initialized sync for hpe/3bp499k1
2020-05-12 20:31:23,200 INFO    MainThread:11642 [run_manager.py:wrap_existing_process():1148] wrapping existing process 11627
2020-05-12 20:31:23,200 WARNING MainThread:11642 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-05-12 20:31:23,422 INFO    MainThread:11642 [run_manager.py:init_run():927] system metrics and metadata threads started
2020-05-12 20:31:23,422 INFO    MainThread:11642 [run_manager.py:init_run():966] upserting run before process can begin, waiting at most 10 seconds
2020-05-12 20:31:23,727 INFO    Thread-14 :11642 [run_manager.py:_upsert_run():1051] saving patches
2020-05-12 20:31:23,773 INFO    Thread-14 :11642 [run_manager.py:_upsert_run():1055] saving pip packages
2020-05-12 20:31:23,774 INFO    Thread-14 :11642 [run_manager.py:_upsert_run():1057] initializing streaming files api
2020-05-12 20:31:23,776 INFO    Thread-14 :11642 [run_manager.py:_upsert_run():1064] unblocking file change observer, beginning sync with W&B servers
2020-05-12 20:31:23,776 INFO    MainThread:11642 [run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2020-05-12 20:31:23,783 INFO    MainThread:11642 [run_manager.py:_sync_etc():1272] entering loop for messages from user process
2020-05-12 20:31:23,787 INFO    MainThread:11642 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1589308283.Datta.11627.0", "policy": "live"}}
2020-05-12 20:31:24,178 INFO    Thread-3  :11642 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/config.yaml
2020-05-12 20:31:24,431 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-metadata.json
2020-05-12 20:31:24,432 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/diff.patch
2020-05-12 20:31:24,433 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/requirements.txt
2020-05-12 20:31:24,434 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/output.log
2020-05-12 20:31:24,434 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/code/src/train.py
2020-05-12 20:31:24,435 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/code
2020-05-12 20:31:24,435 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/code/src
2020-05-12 20:31:24,629 INFO    MainThread:11642 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "Loss_2d_2_3d_Train_Loss_kld_loss/events.out.tfevents.1589308284.Datta.11627.1", "policy": "live"}}
2020-05-12 20:31:24,636 INFO    MainThread:11642 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "Loss_2d_2_3d_Train_Loss_recon_loss/events.out.tfevents.1589308284.Datta.11627.2", "policy": "live"}}
2020-05-12 20:31:25,168 INFO    MainThread:11642 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "Loss_2d_2_3d_Val_Loss_kld_loss/events.out.tfevents.1589308285.Datta.11627.3", "policy": "live"}}
2020-05-12 20:31:25,172 INFO    MainThread:11642 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "Loss_2d_2_3d_Val_Loss_recon_loss/events.out.tfevents.1589308285.Datta.11627.4", "policy": "live"}}
2020-05-12 20:31:25,179 INFO    Thread-3  :11642 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/output.log
2020-05-12 20:31:25,179 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/Loss_2d_2_3d_Val_Loss_recon_loss/events.out.tfevents.1589308285.Datta.11627.4
2020-05-12 20:31:25,180 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/Loss_2d_2_3d_Train_Loss_recon_loss/events.out.tfevents.1589308284.Datta.11627.2
2020-05-12 20:31:25,181 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/Loss_2d_2_3d_Train_Loss_recon_loss
2020-05-12 20:31:25,186 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/Loss_2d_2_3d_Val_Loss_recon_loss
2020-05-12 20:31:25,468 INFO    MainThread:11642 [run_manager.py:_sync_etc():1328] process received interrupt signal, shutting down
2020-05-12 20:31:25,469 INFO    MainThread:11642 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-05-12 20:31:25,470 INFO    MainThread:11642 [run_manager.py:shutdown():1071] shutting down system stats and metadata service
2020-05-12 20:31:26,186 INFO    Thread-3  :11642 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-history.jsonl
2020-05-12 20:31:26,187 INFO    Thread-3  :11642 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/output.log
2020-05-12 20:31:26,191 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-events.jsonl
2020-05-12 20:31:26,192 INFO    Thread-3  :11642 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-summary.json
2020-05-12 20:31:26,431 INFO    MainThread:11642 [run_manager.py:shutdown():1085] stopping streaming files and file change observer
2020-05-12 20:31:27,185 INFO    Thread-3  :11642 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-metadata.json
2020-05-12 20:31:29,493 INFO    MainThread:11642 [run_manager.py:_sync_etc():1393] process only ran for 6 seconds, not syncing files
2 20:31:26,431 INFO    MainThread:11642 [3bp499k1:run_manager.py:shutdown():1085] stopping streaming files and file change observer
2020-05-12 20:31:27,185 INFO    Thread-3  :11642 [3bp499k1:run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200512_183122-3bp499k1/wandb-metadata.json
2020-05-12 20:31:29,493 INFO    MainThread:11642 [3bp499k1:run_manager.py:_sync_etc():1393] process only ran for 6 seconds, not syncing files
